on:
  push:
    branches:
      - main

jobs:
  prod_deploy:
    name: PRODUCTION_DEPLOY
    runs-on: ubuntu-latest
    setps:
      name: hello-world-test
      run: |
        echo "Hello World!"
