on:
    issues:
        types: [opened]
    workflow_dispatch:
        
        
jobs:
    create_comment:
        runs-on: ubuntu-latest
        steps:
        - uses: peter-evans/create-or-update-comment@v3
          name: Creating a comment on issue
          with:
            issue-number: ${{ github.event.issue.number }}
            body: |
                hello world
                - this is a bullet point
        
    
    
