name: hello World workflow


on: 
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  print_hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello World
        run: echo "Hello World"
        shell: bash
  
  print_good_bye:
    runs-on: ubuntu-latest
    steps:
      - name: Good bye the world
        run: echo "Good bye the workd"
        shell: bash