on:
  push:
    branches:
      - main

jobs:
  prod_deploy:
    name: PRODUCTION_DEPLOY
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Tes
    - run: |
        echo "Hello World"